-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCpibH292BFaS4rkm
OhvOD5fnGCsSVUa7MC4WbxChRGugCgYIKoZIzj0DAQehRANCAATTu7kqx0Rx2KBF
MO6JqlMNzORlyHF0/dVcqfuo+F6J4m1yNMo+CiJPGZAdW0PBRxwnUOwHpY1eVHA2
vQjdc0Ay
-----END PRIVATE KEY-----